services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reelreview_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    depends_on:
      - db
    networks:
      - reelreview_network

  db:
    image: mysql:8.0
    container_name: reelreview_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db_reelreview
      MYSQL_USER: reelreview_user
      MYSQL_PASSWORD: reelreview_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - reelreview_db_data:/var/lib/mysql
    networks:
      - reelreview_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: reelreview_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - reelreview_network

networks:
  reelreview_network:

volumes:
  reelreview_db_data:
